version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8080"
    environment:
      - ENV=dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:8080"
